#!/bin/bash

alias vdot="vim ~/.dotfiles"
alias vin="vim -Nu NONE" # Launch vim in no-compatible mode, but with no vimrc
alias open="xdg-open"
alias tgz="tar -xvzf"

alias s="sudo"
alias cl="clear"
alias q="exit"
alias qq="exit"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias -- -="cd -" # Go back to previous directory using -

alias dot="cd ~/.dotfiles"
alias ws="cd ~/Workspace"
alias ql="cd ~/Quicklinks"
alias doc="cd ~/Documents"
alias down="cd ~/Downloads"

alias ls="ls --color=auto --group-directories-first"
alias tree="tree --dirsfirst"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias mkdir="mkdir -p" # Automatically create intermediate non-existing directories when needed

alias v="~/.dotfiles/shell/scripts/v.sh"
alias vs="~/.dotfiles/shell/scripts/vs.sh"
alias za="~/.dotfiles/shell/scripts/za.sh"
alias search="~/.dotfiles/shell/scripts/search.sh"
alias mkql="~/.dotfiles/shell/scripts/mkql.sh"
alias all="~/.dotfiles/shell/scripts/all.sh"

alias cla="all 'clear'"
alias qa="all 'exit'"

alias cd..="cd .."
alias gti="git"
alias igt="git"
alias gt="git"
alias got="git"
alias giut="git"
alias gitu="git"
alias giit="git"
alias gi="git"
alias it="git"
