#!/usr/bin/env bash

# Sets the Base16 Shell theme

# Note: We don't use profiler_helper.sh (from the Base16 Shell repo), because
# it does extra things we don't need (sets global functions like the base16_*
# functions, creates files like .vimrc_background)

source ~/.dotfiles/shell/helpers

# Don't set a Base16 Shell theme if running on ssh since Base16 Shell currently
# has a problem where it doesn't set colors properly when on tmux+ssh
# (see https://github.com/chriskempson/base16-shell/issues/145)
if in_ssh; then
    return 0
fi

theme=~/.config/base16-shell/scripts/base16-onedark.sh
if [ -s "$theme" ]; then
    source $theme
else
    echo "Error: the theme at '$theme' was not found."
fi
