set nocompatible " Enable modern vim features not compatible with vi (must be at the top)

""" Base Defaults
source ~/.dotfiles/vim/sensible.vim " Loaded here instead of via a plugin manager cause plugin managers typically load plugins after vimrc (see https://unix.stackexchange.com/a/74778)

""" Keymaps
source ~/.dotfiles/vim/keymaps.vim

""" Plugins
source ~/.dotfiles/vim/plugins.vim

""" General
set number " Show line numbers on the side bar
set hlsearch " Highlight search results
set ignorecase " Ignore case when searching ...
set smartcase " ... unless search pattern contains upper case characters
set smartindent " Smart autoindenting when starting a new line
set formatoptions=crqlj " Format options that are good for Google style (see :h fo-table)
set list lcs=tab:\ \  " When cursor is on a tab char, go to beginning of tab, not end (Note: the space after the second \ is important) (see :h listchars and https://vi.stackexchange.com/a/2242)
set nowrap " Disable line wrapping by default ...
set linebreak " ... but if enabled, don't break words when wrapping
set noshowmode " Disable the mode status at the bottom
set showcmd " Show last command executed at the bottom
set splitbelow " Open files below the current window when doing a horizontal split
set splitright " Open files to the right of the current window when doing a vertical split
set hidden " Allow for current buffer to be backgrounded
set autoread " Detect when a file is changed
set undofile " Maintain undo history between sessions
set undodir=~/.vim/undo " Save undo history files here instead of where the modified files are
set noswapfile " Don't make swap files
set mouse-=a " Disable mouse click to go to position
set clipboard^=unnamedplus " Use system clipboard for seamless copy-pasting between vim and the system (required: X11 clipboard support, see https://vim.fandom.com/wiki/Accessing_the_system_clipboard#Checking_for_X11-clipboard_support_in_terminal)

autocmd BufNewFile,BufEnter * silent! lcd %:p:h " Auto-change current working directory to that of the current buffer (works better with fzf compared to the 'autochdir' option)

autocmd InsertEnter * :setlocal nohlsearch " Turn off search result highlighting when entering insert mode ...
autocmd InsertLeave * :setlocal hlsearch " ... but turn it back on when leaving insert mode

autocmd FileType * set formatoptions-=o " See :h fo-table for what removing the option 'o' does, and https://vi.stackexchange.com/q/9366 for why we remove it this way here

" Create undo dir if it does not exist
if !isdirectory(&undodir)
  silent call system('mkdir -p ' . &undodir)
endif

""" Tab Control
set expandtab " Replace tabs with spaces
set softtabstop=4 " # of spaces inserted when you hit <TAB> in insert mode, and # of spaces deleted when you hit backspace on a <TAB>
set shiftwidth=4 " # of spaces to use for indenting and unindenting using >> and <<
set tabstop=8 " # of spaces used to visually represent the <TAB> character

autocmd FileType vim setlocal softtabstop=2 shiftwidth=2
autocmd FileType yaml setlocal softtabstop=2 shiftwidth=2
autocmd FileType xml setlocal softtabstop=2 shiftwidth=2
autocmd FileType json setlocal softtabstop=2 shiftwidth=2
autocmd FileType make setlocal noexpandtab shiftwidth=8

""" Colors
set background=dark " Fixes a weird issue with vim-dim where the colorscheme quickly changes from light to dark on start-up

augroup my_colors " Colorscheme overrides (see https://gist.github.com/romainl/379904f91fa40533175dfaec4c833f2f)
  autocmd!
  autocmd Colorscheme * highlight MatchParen cterm=none ctermbg=none ctermfg=blue " Make highlighting used for matching parentheses more distinguishable from the cursor
  autocmd Colorscheme * highlight SignColumn ctermbg=none " Remove highlighting on the gutter (used by plugins like Neomake)
  autocmd Colorscheme * highlight! link VertSplit LineNr " Make vertical split boundaries have the same highlighting as line numbers
  autocmd Colorscheme * highlight! link NonText LineNr " Make NonText characters (:h NonText; e.g. ~ symbols indicating end of buffer) have the same highlighting as line numbers. Note: this also affects characters in listchars (see https://stackoverflow.com/a/1294834)
  autocmd Colorscheme * highlight! link Todo Comment " Make TODO's (and FIXME's, etc.) have the same highlighting as regular comments
augroup END

colorscheme dim " Must go below all autocmds that override the colorscheme (see same github link regarding color overrides)
