# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

HISTCONTROL=ignoredups # Don't save line onto history if it matches the previous line

shopt -s histappend # Append to history file, don't overwrite it
shopt -s globstar # Set pattern "**" to match all files and directories/subdirectories
shopt -s checkwinsize # Check window size after each command and update LINES and COLUMNS if needed

# Make 'less' more friendly for non-text files (see 'man lesspipe')
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Enable programmable completion features
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        source /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        source /etc/bash_completion
    fi
fi

# Set variable identifying the chroot you're working in (used to configure the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# Use color prompt if supported by terminal
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# Configure prompt
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt

# Enable color support for ls
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# Set theme
source ~/.dotfiles/shell/theme

# Set paths
source ~/.dotfiles/shell/path

# Set aliases
source ~/.dotfiles/shell/aliases

# Override what happens when changing directories
function cd() {
    builtin cd -P "$@" # Resolve symlinks to their true values
    ls # Automatically list directory contents
}

# Bash-specific aliases
alias z="SHELL=$(which zsh) zsh" # Launch zsh
alias rl="source ~/.bashrc" # Reload the bash configuration file
alias rla="all 'source ~/.bashrc'" # Reload the bash configuration file on all tmux panes
