#!/usr/bin/env bash

source ~/.dotfiles/shell/helpers

function ssh_prompt() {
    if in_ssh; then
        echo "(ssh) "
    fi
}

# Set chroot identifier
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# Use color prompt if supported by terminal
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# Configure prompt
if [ "$color_prompt" = yes ]; then
    PS1='$(ssh_prompt)${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='$(ssh_prompt)${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt
