#!/usr/bin/env zsh

source ~/.dotfiles/shell/helpers

# Disable auto-update checks for ohmyzsh
DISABLE_AUTO_UPDATE="true"

# Disable auto-escaping of copy-pasted URLs
DISABLE_MAGIC_FUNCTIONS="true"

# Autostart tmux if not running zsh on ssh
if ! in_ssh; then
    ZSH_TMUX_AUTOSTART="true"
fi

ZSH_TMUX_AUTOCONNECT="false"
