#!/usr/bin/env zsh

# Load zgenom for plugin management
# This also loads plugins using a plugin init script if one has been generated
source ~/.zgenom/zgenom.zsh

# If there is no plugin init script, load the plugins and then generate one
# (to delete the init script, run 'zgenom reset'; you must do this when adding/removing plugins)
if ! zgenom saved; then
    echo "Creating new zgenom save"

    zgenom ohmyzsh # Sensible zsh settings + library of themes and plugins (required: zsh 5.1.1+)
    zgenom ohmyzsh plugins/tmux # Tmux integration
    zgenom ohmyzsh plugins/colored-man-pages # Colorize man pages
    zgenom load zsh-users/zsh-autosuggestions # As-you-type autosuggestions
    zgenom load zsh-users/zsh-completions # Additional completion definitions

    zgenom save # Save all to init script
fi
