#!/usr/bin/env zsh

source ~/.dotfiles/shell/helpers

# Disable auto-update checks for ohmyzsh
DISABLE_AUTO_UPDATE="true"

# Disable auto-escaping of copy-pasted URLs
DISABLE_MAGIC_FUNCTIONS="true"

# Autostart tmux if not running zsh on ssh
if ! in_ssh; then
    ZSH_TMUX_AUTOSTART="true"
fi

ZSH_TMUX_AUTOCONNECT="false"

# Fix ohmyzsh's git_prompt_info function (see
# https://github.com/ohmyzsh/ohmyzsh/issues/12328#issuecomment-2400576507 and
# https://github.com/ohmyzsh/ohmyzsh/blob/master/README.md#async-git-prompt)
zstyle ':omz:alpha:lib:git' async-prompt force
