#!/usr/bin/env zsh

# Inspired by the robbyrussell and risto themes from ohmyzsh
# Contains a fix to a bug in robbyrussell that occurs when using zsh plugin managers
# (see https://github.com/zplug/zplug/issues/95)

source ~/.dotfiles/shell/helpers

function ssh_prompt() {
    if in_ssh; then
        echo "(ssh) "
    fi
}

ret_status="%(?:%{$fg[green]%}➜ :%{$fg[red]%}➜ )"

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}(%{$fg_bold[red]%}"
ZSH_THEME_GIT_PROMPT_DIRTY=" %{$fg_bold[yellow]%}*%{$fg_bold[blue]%})"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[blue]%})"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "

PROMPT='$(ssh_prompt)${ret_status} %{$fg_bold[blue]%}%2~ $(git_prompt_info)%{$reset_color%}'
