#!/bin/zsh

# Inspired by the robbyrussell and risto themes from oh-my-zsh
# Contains a fix to a bug in robbyrussell that occurs when using zsh plugin managers
# (see https://github.com/zplug/zplug/issues/95)

ret_status="%(?:%{$fg[green]%}➜ :%{$fg[red]%}➜ )"
PROMPT='${ret_status} %{$fg_bold[blue]%}%2~ $(git_prompt_info)%{$reset_color%}'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}(%{$fg_bold[red]%}"
ZSH_THEME_GIT_PROMPT_DIRTY=" %{$fg_bold[yellow]%}*%{$fg_bold[blue]%})"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[blue]%})"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
