# Load plugin configs (must go before plugins are loaded)
source ~/.dotfiles/shell/zsh/plugin_configs

# Load plugins
source ~/.dotfiles/shell/zsh/plugins

# Set prompt (must go after plugins are loaded since this depends on functions and definitions from ohmyzsh)
source ~/.dotfiles/shell/zsh/prompt

# Set theme
source ~/.dotfiles/shell/theme

# Set env vars
source ~/.dotfiles/shell/env

# Set aliases
source ~/.dotfiles/shell/aliases

# Load fzf integration (must go after envs are loaded since this needs the PATH to contain the fzf binary)
source ~/.dotfiles/shell/zsh/fzf

# Automatically list directory contents when changing directories
function chpwd {
    ls
}

setopt CHASE_LINKS # Resolve symlinks to their true values when changing directory

bindkey "^p" up-line-or-search # Set 'Ctrl + p' to behave like the up-arrow
bindkey "^n" down-line-or-search # Set 'Ctrl + n' to behave like the down-arrow

# Zsh-specific aliases
alias rl='source ~/.zshrc' # Reload the zsh configuration file
alias rla='all "source ~/.zshrc"' # Reload the zsh configuration file on all tmux panes

# Load completions for kubectl if kubectl exists
(( $+commands[kubectl] )) && source <(kubectl completion zsh)
