# Plugin Configs (must go before plugins are loaded)
ZSH_TMUX_AUTOSTART="true"
ZSH_TMUX_AUTOCONNECT="false"

# Load plugins
source ~/.dotfiles/shell/zsh/plugins

# Set the prompt (must go after plugins are loaded since this depends on functions and definitions from oh-my-zsh)
source ~/.dotfiles/shell/zsh/prompt

setopt CHASE_LINKS # Resolve symlinks to their true values when changing directory

bindkey "^p" up-line-or-search # Set 'Ctrl + p' to behave like the up-arrow
bindkey "^n" down-line-or-search # Set 'Ctrl + n' to behave like the down-arrow

# Set theme
source ~/.dotfiles/shell/theme

# Set aliases
source ~/.dotfiles/shell/aliases

# Automatically list directory contents when changing directories
function chpwd() {
    ls
}

# Zsh-specific aliases
alias rl="source ~/.zshrc" # Reload the zsh configuration file
alias rla="all 'source ~/.zshrc'" # Reload the zsh configuration file on all tmux panes
